"""Re-initializing database with correct table names.

Revision ID: b3977c61fd71
Revises: dbabfabf1247
Create Date: 2025-07-31 12:53:36.060308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3977c61fd71'
down_revision = 'dbabfabf1247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('participant1_id', sa.Integer(), nullable=True),
    sa.Column('participant2_id', sa.Integer(), nullable=True),
    sa.Column('score1', sa.Integer(), nullable=True),
    sa.Column('score2', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['participant1_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['participant2_id'], ['participant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('match')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('round_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('participant1_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('participant2_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score1', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score2', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.ForeignKeyConstraint(['participant1_id'], ['participant.id'], name=op.f('match_ibfk_1')),
    sa.ForeignKeyConstraint(['participant2_id'], ['participant.id'], name=op.f('match_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('matches')
    # ### end Alembic commands ###
